const STARS = [
  {
    name: "Sirius",
    ra: 101.287,
    dec: -16.716,
    magnitude: -1.46,
    constellation: "Canis Major",
    distance: 8.6,
    spectralClass: "A1V",
    age: 0.242,
    mass: 2.02,
    description:
      "The brightest star in the night sky, also known as the Dog Star.",
  },
  {
    name: "Canopus",
    ra: 95.988,
    dec: -52.696,
    magnitude: -0.74,
    constellation: "Carina",
    distance: 310,
    spectralClass: "A9II",
    age: 0.028,
    mass: 8.5,
    description:
      "The second brightest star in the night sky, visible mainly from southern latitudes.",
  },
  {
    name: "Arcturus",
    ra: 213.915,
    dec: 19.182,
    magnitude: -0.05,
    constellation: "Boötes",
    distance: 37,
    spectralClass: "K1.5IIIFe-0.5",
    age: 7.1,
    mass: 1.08,
    description:
      "An orange giant star and the brightest star in the northern celestial hemisphere.",
  },
  {
    name: "Vega",
    ra: 279.234,
    dec: 38.784,
    magnitude: 0.03,
    constellation: "Lyra",
    distance: 25,
    spectralClass: "A0V",
    age: 0.455,
    mass: 2.135,
    description: "One of the most luminous stars in the solar neighborhood.",
  },
  {
    name: "Capella",
    ra: 79.172,
    dec: 45.998,
    magnitude: 0.08,
    constellation: "Auriga",
    distance: 43,
    spectralClass: "G3III",
    age: 0.59,
    mass: 2.57,
    description:
      "Actually a complex multiple star system of four stars in two binary pairs.",
  },
  {
    name: "Rigel",
    ra: 78.634,
    dec: -8.202,
    magnitude: 0.13,
    constellation: "Orion",
    distance: 860,
    spectralClass: "B8Ia",
    age: 0.008,
    mass: 21,
    description:
      "A blue supergiant star and the brightest star in the constellation Orion.",
  },
  {
    name: "Procyon",
    ra: 114.825,
    dec: 5.225,
    magnitude: 0.34,
    constellation: "Canis Minor",
    distance: 11.5,
    spectralClass: "F5IV",
    age: 1.87,
    mass: 1.499,
    description: "The eighth brightest star in Earth's night sky.",
  },
  {
    name: "Betelgeuse",
    ra: 88.793,
    dec: 7.407,
    magnitude: 0.5,
    constellation: "Orion",
    distance: 650,
    spectralClass: "M1-2Ia",
    age: 0.01,
    mass: 16.5,
    description: "A red supergiant star expected to explode as a supernova.",
  },
  {
    name: "Achernar",
    ra: 24.429,
    dec: -57.237,
    magnitude: 0.46,
    constellation: "Eridanus",
    distance: 139,
    spectralClass: "B6Vep",
    age: 0.037,
    mass: 6.7,
    description: "The flattest known star due to its extremely rapid rotation.",
  },
  {
    name: "Altair",
    ra: 297.696,
    dec: 8.868,
    magnitude: 0.77,
    constellation: "Aquila",
    distance: 17,
    spectralClass: "A7V",
    age: 1.0,
    mass: 1.79,
    description: "One of the vertices of the Summer Triangle asterism.",
  },
  {
    name: "Aldebaran",
    ra: 68.98,
    dec: 16.51,
    magnitude: 0.85,
    constellation: "Taurus",
    distance: 65,
    spectralClass: "K5III",
    age: 6.4,
    mass: 1.16,
    description:
      "The orange giant that appears to be the brightest star in the Hyades cluster.",
  },
  {
    name: "Spica",
    ra: 201.3,
    dec: -11.16,
    magnitude: 1.04,
    constellation: "Virgo",
    distance: 250,
    spectralClass: "B1III",
    age: 0.01,
    mass: 10.25,
    description: "A binary star system and the brightest star in Virgo.",
  },
  {
    name: "Antares",
    ra: 247.35,
    dec: -26.43,
    magnitude: 1.09,
    constellation: "Scorpius",
    distance: 600,
    spectralClass: "M1.5Iab",
    age: 0.011,
    mass: 12,
    description: "A red supergiant, one of the largest known stars.",
  },
  {
    name: "Fomalhaut",
    ra: 344.41,
    dec: -29.62,
    magnitude: 1.16,
    constellation: "Piscis Austrinus",
    distance: 25,
    spectralClass: "A3V",
    age: 0.44,
    mass: 1.92,
    description: "A young star surrounded by a debris disk.",
  },
  {
    name: "Deneb",
    ra: 310.36,
    dec: 45.28,
    magnitude: 1.25,
    constellation: "Cygnus",
    distance: 2600,
    spectralClass: "A2Ia",
    age: 0.01,
    mass: 19,
    description:
      "One of the most luminous stars known, part of the Summer Triangle.",
  },
  {
    name: "Regulus",
    ra: 152.09,
    dec: 11.97,
    magnitude: 1.35,
    constellation: "Leo",
    distance: 77,
    spectralClass: "B7V",
    age: 0.05,
    mass: 3.8,
    description: "The brightest star in Leo, known as the 'heart of the lion'.",
  },
  {
    name: "Adhara",
    ra: 104.656,
    dec: -28.972,
    magnitude: 1.5,
    constellation: "Canis Major",
    distance: 430,
    spectralClass: "B2II",
    age: 0.022,
    mass: 12.5,
    description: "The second brightest star in Canis Major.",
  },
  {
    name: "Castor",
    ra: 113.65,
    dec: 31.89,
    magnitude: 1.57,
    constellation: "Gemini",
    distance: 51,
    spectralClass: "A1V",
    age: 0.37,
    mass: 2.76,
    description: "A complex multiple star system in Gemini.",
  },
  {
    name: "Shaula",
    ra: 263.402,
    dec: -37.104,
    magnitude: 1.63,
    constellation: "Scorpius",
    distance: 700,
    spectralClass: "B1.5IV",
    age: 0.025,
    mass: 14.5,
    description: "The stinger of the Scorpion.",
  },
  {
    name: "Bellatrix",
    ra: 81.28,
    dec: 6.35,
    magnitude: 1.64,
    constellation: "Orion",
    distance: 245,
    spectralClass: "B2III",
    age: 0.025,
    mass: 8.6,
    description: "The third brightest star in Orion constellation.",
  },
  {
    name: "Elnath",
    ra: 81.573,
    dec: 28.608,
    magnitude: 1.68,
    constellation: "Taurus",
    distance: 130,
    spectralClass: "B7III",
    age: 0.1,
    mass: 5.0,
    description: "The second brightest star in Taurus.",
  },
  {
    name: "Miaplacidus",
    ra: 138.3,
    dec: -69.717,
    magnitude: 1.68,
    constellation: "Carina",
    distance: 110,
    spectralClass: "A1III",
    age: 0.26,
    mass: 3.5,
    description: "The second brightest star in Carina.",
  },
  {
    name: "Alnilam",
    ra: 84.053,
    dec: -1.202,
    magnitude: 1.69,
    constellation: "Orion",
    distance: 2000,
    spectralClass: "B0Ia",
    age: 0.004,
    mass: 32,
    description: "The middle star of Orion's Belt.",
  },
  {
    name: "Alnair",
    ra: 332.058,
    dec: -46.961,
    magnitude: 1.74,
    constellation: "Grus",
    distance: 100,
    spectralClass: "B7IV",
    age: 0.1,
    mass: 4.0,
    description: "The brightest star in Grus.",
  },
  {
    name: "Alioth",
    ra: 193.507,
    dec: 55.96,
    magnitude: 1.77,
    constellation: "Ursa Major",
    distance: 81,
    spectralClass: "A1III",
    age: 0.3,
    mass: 2.91,
    description: "The brightest star in the Big Dipper.",
  },
  {
    name: "Alnitak",
    ra: 85.19,
    dec: -1.943,
    magnitude: 1.79,
    constellation: "Orion",
    distance: 800,
    spectralClass: "O9.5Ib",
    age: 0.006,
    mass: 33,
    description: "The easternmost star of Orion's Belt.",
  },
  {
    name: "Dubhe",
    ra: 165.932,
    dec: 61.751,
    magnitude: 1.79,
    constellation: "Ursa Major",
    distance: 120,
    spectralClass: "K3III",
    age: 4.25,
    mass: 4.25,
    description: "One of the pointer stars of the Big Dipper.",
  },
  {
    name: "Mirfak",
    ra: 51.081,
    dec: 49.861,
    magnitude: 1.8,
    constellation: "Perseus",
    distance: 590,
    spectralClass: "F5Ib",
    age: 0.041,
    mass: 8.5,
    description: "The brightest star in Perseus.",
  },
  {
    name: "Wezen",
    ra: 107.098,
    dec: -26.393,
    magnitude: 1.84,
    constellation: "Canis Major",
    distance: 1800,
    spectralClass: "F8Ia",
    age: 0.01,
    mass: 16.9,
    description: "A yellow supergiant in Canis Major.",
  },
  {
    name: "Sargas",
    ra: 265.622,
    dec: -42.998,
    magnitude: 1.87,
    constellation: "Scorpius",
    distance: 270,
    spectralClass: "F1II",
    age: 0.09,
    mass: 5.7,
    description: "Also known as Theta Scorpii.",
  },
  {
    name: "Kaus Australis",
    ra: 276.043,
    dec: -34.385,
    magnitude: 1.85,
    constellation: "Sagittarius",
    distance: 140,
    spectralClass: "B9.5III",
    age: 0.232,
    mass: 3.5,
    description: "The brightest star in Sagittarius.",
  },
  {
    name: "Avior",
    ra: 125.628,
    dec: -59.51,
    magnitude: 1.86,
    constellation: "Carina",
    distance: 630,
    spectralClass: "K3III",
    age: 0.955,
    mass: 9.0,
    description: "An orange giant in Carina.",
  },
  {
    name: "Alkaid",
    ra: 206.885,
    dec: 49.313,
    magnitude: 1.86,
    constellation: "Ursa Major",
    distance: 100,
    spectralClass: "B3V",
    age: 0.01,
    mass: 6.1,
    description: "The end star of the Big Dipper's handle.",
  },
  {
    name: "Menkalinan",
    ra: 89.93,
    dec: 44.947,
    magnitude: 1.9,
    constellation: "Auriga",
    distance: 81,
    spectralClass: "A1IV",
    age: 0.57,
    mass: 2.39,
    description: "The second brightest star in Auriga.",
  },
  {
    name: "Atria",
    ra: 253.416,
    dec: -69.028,
    magnitude: 1.92,
    constellation: "Triangulum Australe",
    distance: 420,
    spectralClass: "K2IIIa",
    age: 0.048,
    mass: 7.0,
    description: "The brightest star in Triangulum Australe.",
  },
  {
    name: "Alhena",
    ra: 99.428,
    dec: 16.399,
    magnitude: 1.93,
    constellation: "Gemini",
    distance: 100,
    spectralClass: "A1.5IV",
    age: 0.46,
    mass: 2.81,
    description: "The third brightest star in Gemini.",
  },
  {
    name: "Peacock",
    ra: 306.412,
    dec: -56.735,
    magnitude: 1.94,
    constellation: "Pavo",
    distance: 180,
    spectralClass: "B2IV",
    age: 0.018,
    mass: 5.9,
    description: "The brightest star in Pavo.",
  },
  {
    name: "Alsephina",
    ra: 218.877,
    dec: 14.572,
    magnitude: 1.95,
    constellation: "Virgo",
    distance: 260,
    spectralClass: "A1V",
    age: 0.2,
    mass: 2.4,
    description: "Also known as Delta Virginis.",
  },
  {
    name: "Mirzam",
    ra: 95.674,
    dec: -17.956,
    magnitude: 1.98,
    constellation: "Canis Major",
    distance: 500,
    spectralClass: "B1II-III",
    age: 0.012,
    mass: 13.5,
    description: "Also known as Beta Canis Majoris.",
  },
  {
    name: "Polaris",
    ra: 37.95,
    dec: 89.26,
    magnitude: 1.98,
    constellation: "Ursa Minor",
    distance: 433,
    spectralClass: "F7Ib",
    age: 0.07,
    mass: 5.4,
    description: "The current north pole star, used for navigation.",
  },
  {
    name: "Alphard",
    ra: 141.897,
    dec: -8.658,
    magnitude: 1.98,
    constellation: "Hydra",
    distance: 180,
    spectralClass: "K3II-III",
    age: 0.42,
    mass: 3.0,
    description: "The brightest star in Hydra, known as the 'solitary one'.",
  },
  {
    name: "Hamal",
    ra: 31.793,
    dec: 23.462,
    magnitude: 2.0,
    constellation: "Aries",
    distance: 66,
    spectralClass: "K2IIIa",
    age: 3.4,
    mass: 1.5,
    description: "The brightest star in Aries.",
  },
  {
    name: "Algieba",
    ra: 154.993,
    dec: 19.842,
    magnitude: 2.08,
    constellation: "Leo",
    distance: 130,
    spectralClass: "K1III",
    age: 1.2,
    mass: 1.23,
    description: "A double star system in Leo.",
  },
  {
    name: "Diphda",
    ra: 10.897,
    dec: -17.987,
    magnitude: 2.04,
    constellation: "Cetus",
    distance: 96,
    spectralClass: "K0III",
    age: 2.9,
    mass: 2.8,
    description: "The brightest star in Cetus.",
  },
  {
    name: "Mizar",
    ra: 200.98,
    dec: 54.93,
    magnitude: 2.04,
    constellation: "Ursa Major",
    distance: 83,
    spectralClass: "A2V",
    age: 0.37,
    mass: 2.5,
    description: "Famous double star in the handle of the Big Dipper.",
  },
  {
    name: "Nunki",
    ra: 283.816,
    dec: -26.297,
    magnitude: 2.05,
    constellation: "Sagittarius",
    distance: 220,
    spectralClass: "B2.5V",
    age: 0.032,
    mass: 7.8,
    description: "The second brightest star in Sagittarius.",
  },
  {
    name: "Menkent",
    ra: 211.671,
    dec: -36.37,
    magnitude: 2.06,
    constellation: "Centaurus",
    distance: 61,
    spectralClass: "K0III",
    age: 4.9,
    mass: 2.06,
    description: "Also known as Theta Centauri.",
  },
  {
    name: "Alpheratz",
    ra: 2.097,
    dec: 29.091,
    magnitude: 2.06,
    constellation: "Andromeda",
    distance: 97,
    spectralClass: "B8IV",
    age: 0.06,
    mass: 3.8,
    description: "The brightest star in Andromeda.",
  },
  {
    name: "Sadr",
    ra: 305.557,
    dec: 40.257,
    magnitude: 2.2,
    constellation: "Cygnus",
    distance: 1500,
    spectralClass: "F8Ib",
    age: 0.012,
    mass: 12,
    description: "The central star of the Northern Cross in Cygnus.",
  },
  {
    name: "Eltanin",
    ra: 269.152,
    dec: 51.489,
    magnitude: 2.23,
    constellation: "Draco",
    distance: 150,
    spectralClass: "K5III",
    age: 0.375,
    mass: 1.72,
    description: "The brightest star in Draco.",
  },
  {
    name: "Schedar",
    ra: 10.127,
    dec: 56.537,
    magnitude: 2.23,
    constellation: "Cassiopeia",
    distance: 230,
    spectralClass: "K0IIIa",
    age: 0.1,
    mass: 4.18,
    description: "The brightest star in Cassiopeia.",
  },
  {
    name: "Naos",
    ra: 120.896,
    dec: -40.003,
    magnitude: 2.25,
    constellation: "Puppis",
    distance: 1080,
    spectralClass: "O4If",
    age: 0.004,
    mass: 22.5,
    description: "The brightest star in Puppis.",
  },
  {
    name: "Almach",
    ra: 30.975,
    dec: 42.33,
    magnitude: 2.26,
    constellation: "Andromeda",
    distance: 350,
    spectralClass: "K3IIb",
    age: 0.3,
    mass: 2.3,
    description: "A colorful multiple star system.",
  },
  {
    name: "Caph",
    ra: 2.295,
    dec: 59.15,
    magnitude: 2.27,
    constellation: "Cassiopeia",
    distance: 54,
    spectralClass: "F2III-IV",
    age: 1.2,
    mass: 1.91,
    description: "The second brightest star in Cassiopeia.",
  },
  {
    name: "Izar",
    ra: 210.955,
    dec: 27.074,
    magnitude: 2.37,
    constellation: "Boötes",
    distance: 200,
    spectralClass: "K0II-III",
    age: 0.037,
    mass: 4.6,
    description: "A beautiful double star system.",
  },
  {
    name: "Dschubba",
    ra: 240.083,
    dec: -22.622,
    magnitude: 2.29,
    constellation: "Scorpius",
    distance: 400,
    spectralClass: "B0.3IV",
    age: 0.011,
    mass: 12,
    description: "Also known as Delta Scorpii.",
  },
  {
    name: "Larawag",
    ra: 295.024,
    dec: -29.88,
    magnitude: 2.6,
    constellation: "Sagittarius",
    distance: 140,
    spectralClass: "B8III",
    age: 0.1,
    mass: 3.5,
    description: "Also known as Epsilon Sagittarii.",
  },
  {
    name: "Merak",
    ra: 178.458,
    dec: 56.382,
    magnitude: 2.37,
    constellation: "Ursa Major",
    distance: 79,
    spectralClass: "A1IVp",
    age: 0.5,
    mass: 2.7,
    description: "One of the pointer stars of the Big Dipper.",
  },
  {
    name: "Ankaa",
    ra: 6.571,
    dec: -42.306,
    magnitude: 2.39,
    constellation: "Phoenix",
    distance: 85,
    spectralClass: "K0.5IIIb",
    age: 5.1,
    mass: 2.4,
    description: "The brightest star in Phoenix.",
  },
  {
    name: "Girtab",
    ra: 262.691,
    dec: -39.03,
    magnitude: 2.41,
    constellation: "Scorpius",
    distance: 65,
    spectralClass: "B2IV",
    age: 0.025,
    mass: 4.6,
    description: "Also known as Kappa Scorpii.",
  },
  {
    name: "Enif",
    ra: 326.046,
    dec: 9.875,
    magnitude: 2.39,
    constellation: "Pegasus",
    distance: 670,
    spectralClass: "K2Ib",
    age: 0.02,
    mass: 12,
    description: "The brightest star in Pegasus.",
  },
  {
    name: "Scheat",
    ra: 345.944,
    dec: 28.083,
    magnitude: 2.42,
    constellation: "Pegasus",
    distance: 200,
    spectralClass: "M2.5II-III",
    age: 0.1,
    mass: 2.1,
    description: "A red giant in Pegasus.",
  },
  {
    name: "Sabik",
    ra: 258.035,
    dec: -15.725,
    magnitude: 2.43,
    constellation: "Ophiuchus",
    distance: 84,
    spectralClass: "A2V",
    age: 1.22,
    mass: 2.4,
    description: "Also known as Eta Ophiuchi.",
  },
  {
    name: "Phecda",
    ra: 183.856,
    dec: 53.695,
    magnitude: 2.44,
    constellation: "Ursa Major",
    distance: 84,
    spectralClass: "A0Ve",
    age: 0.3,
    mass: 2.94,
    description: "Part of the Big Dipper bowl.",
  },
  {
    name: "Aludra",
    ra: 111.024,
    dec: -29.303,
    magnitude: 2.45,
    constellation: "Canis Major",
    distance: 2000,
    spectralClass: "B5Ia",
    age: 0.018,
    mass: 19.19,
    description: "A blue supergiant in Canis Major.",
  },
  {
    name: "Markab",
    ra: 346.19,
    dec: 15.205,
    magnitude: 2.49,
    constellation: "Pegasus",
    distance: 140,
    spectralClass: "B9III",
    age: 0.1,
    mass: 3.5,
    description: "One of the four stars of the Great Square of Pegasus.",
  },
  {
    name: "Denebola",
    ra: 177.265,
    dec: 14.572,
    magnitude: 2.14,
    constellation: "Leo",
    distance: 36,
    spectralClass: "A3V",
    age: 0.4,
    mass: 1.78,
    description: "The tail of the Lion.",
  },
  {
    name: "Algol",
    ra: 47.042,
    dec: 40.956,
    magnitude: 2.12,
    constellation: "Perseus",
    distance: 90,
    spectralClass: "B8V",
    age: 0.57,
    mass: 3.17,
    description: "The famous eclipsing binary star.",
  },
  {
    name: "Capulus",
    ra: 56.457,
    dec: 24.368,
    magnitude: 2.85,
    constellation: "Perseus",
    distance: 550,
    spectralClass: "B1III",
    age: 0.015,
    mass: 9.5,
    description: "Also known as 35 Persei.",
  },
  {
    name: "Rigil Kent",
    ra: 219.902,
    dec: -60.834,
    magnitude: -0.27,
    constellation: "Centaurus",
    distance: 4.4,
    spectralClass: "G2V",
    age: 5.3,
    mass: 1.1,
    description: "Alpha Centauri A, closest star system to Earth.",
  },
  {
    name: "Toliman",
    ra: 219.9,
    dec: -60.835,
    magnitude: 1.33,
    constellation: "Centaurus",
    distance: 4.4,
    spectralClass: "K1V",
    age: 5.3,
    mass: 0.907,
    description: "Alpha Centauri B, companion to Rigil Kent.",
  },
  {
    name: "Gacrux",
    ra: 187.791,
    dec: -57.113,
    magnitude: 1.63,
    constellation: "Crux",
    distance: 88,
    spectralClass: "M3.5III",
    age: 0.1,
    mass: 1.5,
    description: "The red giant at the top of the Southern Cross.",
  },
  {
    name: "Acrux",
    ra: 186.65,
    dec: -63.099,
    magnitude: 0.77,
    constellation: "Crux",
    distance: 320,
    spectralClass: "B0.5IV",
    age: 0.01,
    mass: 17.8,
    description: "The brightest star in the Southern Cross.",
  },
  {
    name: "Becrux",
    ra: 191.93,
    dec: -59.689,
    magnitude: 1.25,
    constellation: "Crux",
    distance: 280,
    spectralClass: "B0.5III",
    age: 0.008,
    mass: 16,
    description: "The second brightest star in the Southern Cross.",
  },
  {
    name: "Imai",
    ra: 192.64,
    dec: -59.042,
    magnitude: 2.8,
    constellation: "Crux",
    distance: 370,
    spectralClass: "B2IV",
    age: 0.018,
    mass: 8.9,
    description: "Also known as Delta Crucis.",
  },
  {
    name: "Ginan",
    ra: 192.913,
    dec: -57.806,
    magnitude: 4.03,
    constellation: "Crux",
    distance: 88,
    spectralClass: "F2III",
    age: 1.6,
    mass: 1.42,
    description: "Also known as Epsilon Crucis.",
  },
  {
    name: "Muhlifain",
    ra: 205.998,
    dec: -47.388,
    magnitude: 2.3,
    constellation: "Centaurus",
    distance: 380,
    spectralClass: "B1III",
    age: 0.012,
    mass: 12.8,
    description: "Also known as Gamma Centauri.",
  },
  {
    name: "Aspidiske",
    ra: 140.528,
    dec: -64.394,
    magnitude: 2.74,
    constellation: "Carina",
    distance: 690,
    spectralClass: "A8Ib",
    age: 0.053,
    mass: 7.0,
    description: "Also known as Iota Carinae.",
  },
  {
    name: "Suhail",
    ra: 136.999,
    dec: -43.433,
    magnitude: 2.21,
    constellation: "Vela",
    distance: 840,
    spectralClass: "K5Ib",
    age: 0.032,
    mass: 7.7,
    description: "Also known as Lambda Velorum.",
  },
  {
    name: "Alphecca",
    ra: 233.672,
    dec: 26.715,
    magnitude: 2.23,
    constellation: "Corona Borealis",
    distance: 75,
    spectralClass: "A0V",
    age: 0.314,
    mass: 2.58,
    description: "The brightest star in the Northern Crown.",
  },
  {
    name: "Mintaka",
    ra: 83.002,
    dec: -0.299,
    magnitude: 2.23,
    constellation: "Orion",
    distance: 900,
    spectralClass: "O9.5II",
    age: 0.007,
    mass: 24,
    description: "The westernmost star of Orion's Belt.",
  },
  {
    name: "Saph",
    ra: 78.265,
    dec: -9.67,
    magnitude: 2.09,
    constellation: "Orion",
    distance: 720,
    spectralClass: "B0.5Ia",
    age: 0.006,
    mass: 15.5,
    description: "Also known as Kappa Orionis.",
  },
  {
    name: "Kochab",
    ra: 222.676,
    dec: 74.156,
    magnitude: 2.08,
    constellation: "Ursa Minor",
    distance: 130,
    spectralClass: "K4III",
    age: 2.95,
    mass: 2.2,
    description: "The second brightest star in the Little Dipper.",
  },
  {
    name: "Rasalhague",
    ra: 263.734,
    dec: 12.56,
    magnitude: 2.08,
    constellation: "Ophiuchus",
    distance: 47,
    spectralClass: "A5III",
    age: 0.74,
    mass: 2.4,
    description: "The brightest star in Ophiuchus.",
  },
  {
    name: "Rasalgethi",
    ra: 258.662,
    dec: 14.39,
    magnitude: 3.48,
    constellation: "Hercules",
    distance: 360,
    spectralClass: "M5Ib-II",
    age: 0.007,
    mass: 7.3,
    description: "A red supergiant variable star in Hercules.",
  },
  {
    name: "Kornephoros",
    ra: 247.555,
    dec: 21.49,
    magnitude: 2.77,
    constellation: "Hercules",
    distance: 140,
    spectralClass: "G7III",
    age: 3.0,
    mass: 2.9,
    description: "The brightest star in Hercules.",
  },
  {
    name: "Zubenelgenubi",
    ra: 222.72,
    dec: -16.042,
    magnitude: 2.75,
    constellation: "Libra",
    distance: 77,
    spectralClass: "A3IV",
    age: 1.0,
    mass: 2.2,
    description: "The southern claw of Libra.",
  },
  {
    name: "Zubeneschamali",
    ra: 229.252,
    dec: -9.383,
    magnitude: 2.61,
    constellation: "Libra",
    distance: 185,
    spectralClass: "B8V",
    age: 0.2,
    mass: 3.5,
    description: "The northern claw of Libra.",
  },
  {
    name: "Unukalhai",
    ra: 236.067,
    dec: 6.426,
    magnitude: 2.65,
    constellation: "Serpens",
    distance: 74,
    spectralClass: "K2III",
    age: 3.2,
    mass: 2.7,
    description: "The brightest star in Serpens.",
  },
  {
    name: "Lesath",
    ra: 262.97,
    dec: -37.296,
    magnitude: 2.7,
    constellation: "Scorpius",
    distance: 520,
    spectralClass: "B2IV",
    age: 0.018,
    mass: 11.1,
    description: "Close companion to Shaula in Scorpius.",
  },
  {
    name: "Yed Prior",
    ra: 255.132,
    dec: -3.694,
    magnitude: 2.74,
    constellation: "Ophiuchus",
    distance: 170,
    spectralClass: "M0.5III",
    age: 1.8,
    mass: 1.5,
    description: "Also known as Delta Ophiuchi.",
  },
  {
    name: "Yed Posterior",
    ra: 256.329,
    dec: -4.693,
    magnitude: 2.98,
    constellation: "Ophiuchus",
    distance: 110,
    spectralClass: "K0III",
    age: 3.0,
    mass: 2.9,
    description: "Also known as Epsilon Ophiuchi.",
  },
  {
    name: "Han",
    ra: 290.972,
    dec: 41.868,
    magnitude: 3.21,
    constellation: "Ophiuchus",
    distance: 460,
    spectralClass: "A2V",
    age: 0.2,
    mass: 2.0,
    description: "Also known as Zeta Ophiuchi.",
  },
];

console.log("Star data loaded:", STARS.length, "stars");
